#!/usr/bin/env node
import * as fs from 'node:fs'
import * as path from 'node:path'

const modulesPath = path.join(process.cwd(), 'src', 'modules')
const outputPath = path.join(process.cwd(), 'src', 'core', 'db', 'modules-schema.ts')

function findSchemaFiles(dir: string): string[] {
  const results: string[] = []

  if (!fs.existsSync(dir)) {
    return results
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)

    if (entry.isDirectory()) {
      const modelsPath = path.join(fullPath, 'models')
      if (fs.existsSync(modelsPath)) {
        const schemaFile = path.join(modelsPath, `${entry.name}.schema.ts`)
        if (fs.existsSync(schemaFile)) {
          results.push(entry.name)
        }
      }
    }
  }

  return results
}

const modules = findSchemaFiles(modulesPath)

if (modules.length === 0) {
  console.log('No module schemas found')
  process.exit(0)
}

const content = `// Auto-generated by sync-schema.ts - DO NOT EDIT
// This file exports all module schemas

${modules.map(m => `export * from '@/modules/${m}/models'`).join('\n')}
`

fs.writeFileSync(outputPath, content)

console.log(`✅ Synced ${modules.length} module schemas:`)
modules.forEach(m => console.log(`   - ${m}`))
